<%@ Page Title="Home Page" Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="WebAppCaptureXML_Zafir._Default" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            text-align: right;
            width: 128px;
        }

        .auto-style2 {
            text-align: right;
            width: 128px;
            height: 30px;
        }

        .auto-style3 {
            height: 30px;
        }
    </style>
</head>
<body>

    <form id="form1" runat="server">
        <div>
            <br />
            <table style="width: 100%;">
                <tr>
                    <td class="auto-style2">First Name:</td>
                    <td class="auto-style3">
                        <asp:TextBox ID="tbFname" runat="server"></asp:TextBox>
                        <asp:RequiredFieldValidator ValidationGroup="submitClick" ID="RequiredFieldValidator1" ControlToValidate="tbFname" runat="server" ErrorMessage="First Name is required" Display="Dynamic" ForeColor="Red"></asp:RequiredFieldValidator>
                        <asp:RegularExpressionValidator ValidationGroup="submitClick" ID="RegularExpressionValidator1" ControlToValidate="tbFname" runat="server" ValidationExpression="^[a-zA-Z ]+$" ErrorMessage=" First Name can only contain Alphabets" Display="Dynamic" ForeColor="Red"
                            EnableClientScript="true" SetFocusOnError="True"></asp:RegularExpressionValidator>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style1">Surname</td>
                    <td>
                        <asp:TextBox ID="tbSurname" runat="server"></asp:TextBox>
                        <asp:RequiredFieldValidator ValidationGroup="submitClick" ID="RequiredFieldValidator2" ControlToValidate="tbSurname" runat="server" ErrorMessage="Surname is required" Display="Dynamic" ForeColor="Red"></asp:RequiredFieldValidator>
                        <asp:RegularExpressionValidator ValidationGroup="submitClick" ID="RegularExpressionValidator2" ControlToValidate="tbSurname" ValidationExpression="^[a-zA-Z ]+$" ErrorMessage=" Surname can only contain Alphabets" runat="server" Display="Dynamic" ForeColor="Red" SetFocusOnError="True"></asp:RegularExpressionValidator>
                    </td>
                </tr>
                <tr>
                    <!--Assumed calls within Mauritius Island only, so no symbols or spacebar allowed !-->
                    <td class="auto-style1">Cellphone Number</td>
                    <td>
                        <asp:TextBox ID="tbNumber" runat="server"></asp:TextBox>
                        <asp:RequiredFieldValidator ValidationGroup="submitClick" ID="RequiredFieldValidator3" ControlToValidate="tbNumber" runat="server" ErrorMessage="Cellphone Number is required" Display="Dynamic" ForeColor="Red"></asp:RequiredFieldValidator>
                        <asp:RegularExpressionValidator ValidationGroup="submitClick" ID="RegularExpressionValidator3" runat="server" ValidationExpression="^[0-9]*$" ErrorMessage="Cellphone Number can only contain numeric characters" ControlToValidate="tbNumber" Display="Dynamic" ForeColor="Red"></asp:RegularExpressionValidator>
                        <asp:RegularExpressionValidator ID="RegularExpCount3" ValidationGroup="submitClick" runat="server" ControlToValidate="tbNumber"  ValidationExpression="^([\S\s]{7,8})$"  ErrorMessage="Please enter between 7-8 characters for cellphone number"  Display="Dynamic" ForeColor="Red"> </asp:RegularExpressionValidator>
                    </td>
                </tr>
            </table>
            &nbsp&nbsp<asp:Button ID="btnSubmit" runat="server" Text="Submit"
                OnClick="btnSubmit_Click" />
            <div>
                <asp:GridView ID="gvListPersonsRecords" runat="server" AutoGenerateColumns="False"
                    AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="id"
                    OnRowCancelingEdit="GridView1_RowCancelingEdit"
                    OnRowEditing="GridView1_RowEditing"
                    OnRowUpdating="GridView1_RowUpdating" BackColor="White"
                    OnRowDeleting="XmlGridView_RowDeleting"
                    BorderColor="White" BorderStyle="Ridge" BorderWidth="2px" CellPadding="3"
                    CellSpacing="1" GridLines="None">
                    <Columns>
                        <asp:TemplateField HeaderText="Name">
                            <EditItemTemplate>
                                <asp:TextBox ID="txtFirstName" runat="server" Text='<%# Bind("First_Name") %>'></asp:TextBox>
                                <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="txtFirstName" ForeColor="Red"  Display="Dynamic" ErrorMessage="Name Field can't be blanked"></asp:RequiredFieldValidator>
                                                  <asp:RegularExpressionValidator ID="RegularExpressionValidator1" ControlToValidate="txtFirstName" runat="server" ValidationExpression="^[a-zA-Z ]+$" ErrorMessage=" First Name can only contain Alphabets" Display="Dynamic" ForeColor="Red"
                            EnableClientScript="true" SetFocusOnError="True"></asp:RegularExpressionValidator>

                                </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="LblFirstName" runat="server" Text='<%# Bind("First_Name") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Surname">
                            <EditItemTemplate>
                                <asp:TextBox ID="txtSurname" runat="server" Text='<%# Bind("surname") %>'></asp:TextBox>
                                <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ControlToValidate="txtSurname" ForeColor="Red" ErrorMessage="Email Field can't be blanked" Display="Dynamic"></asp:RequiredFieldValidator>
                                <asp:RegularExpressionValidator ID="RegularExpressionValidator3" ControlToValidate="txtSurname" runat="server" ValidationExpression="^[a-zA-Z ]+$" ErrorMessage="Surname can only contain Alphabets" Display="Dynamic" ForeColor="Red"
                                    EnableClientScript="true" SetFocusOnError="True"></asp:RegularExpressionValidator>

                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblSurname" runat="server" Text='<%# Bind("surname") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Cellphone Number">
                            <EditItemTemplate>
                                <asp:TextBox ID="txtCellphone" runat="server" Text='<%# Bind("Cellphone_Number") %>'></asp:TextBox>
                                <asp:RequiredFieldValidator ID="RequiredFieldValidator4" runat="server" ControlToValidate="txtCellphone" ForeColor="Red" ErrorMessage="Cellphone Number can't be blanked" Display="Dynamic" ></asp:RequiredFieldValidator>
                                <asp:RegularExpressionValidator ID="RegularExpressionValidator10" runat="server" ControlToValidate="txtCellphone"  ValidationExpression="^([\S\s]{7,8})$"  ErrorMessage="Please enter between 7-8 characters for cellphone number"  Display="Dynamic" ForeColor="Red" EnableClientScript="true"> </asp:RegularExpressionValidator>
                                  <asp:RegularExpressionValidator ID="RegularExpressionValidator11" runat="server" ValidationExpression="^[0-9]*$" ErrorMessage="Cellphone Number can only contain numeric characters" ControlToValidate="txtCellphone" Display="Dynamic" ForeColor="Red" EnableClientScript="true"></asp:RegularExpressionValidator>
    
                                </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblCellphoneNumber" runat="server" Text='<%# Bind("Cellphone_Number") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                    <FooterStyle BackColor="#C6C3C6" ForeColor="Black" />
                    <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#E7E7FF" />
                    <PagerStyle BackColor="#C6C3C6" ForeColor="Black" HorizontalAlign="Right" />
                    <RowStyle BackColor="#DEDFDE" ForeColor="Black" />
                    <SelectedRowStyle BackColor="#9471DE" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#F1F1F1" />
                    <SortedAscendingHeaderStyle BackColor="#594B9C" />
                    <SortedDescendingCellStyle BackColor="#CAC9C9" />
                    <SortedDescendingHeaderStyle BackColor="#33276A" />
                </asp:GridView>
            </div>
            <div>
                <asp:Label ID="lblresult" runat="server"></asp:Label>
            </div>
        </div>
    </form>
</body>
</html>

